# Generated by Django 3.1.2 on 2020-11-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='workout_distance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='workout_time',
            field=models.IntegerField(default=0),
        ),
    ]
