# Generated by Django 3.1.3 on 2020-11-21 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_city_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=75)),
                ('description', models.TextField()),
                ('sport', models.CharField(choices=[('Cycling', 'Cycling'), ('Hiking', 'Hiking'), ('Lifting Weights', 'Lifting Weights'), ('Running', 'Running'), ('Swimming', 'Swimming'), ('Walking', 'Walking'), ('Yoga', 'Yoga')], default='Running', max_length=15)),
                ('type', models.CharField(choices=[('Distance', 'Distance'), ('Interval', 'Interval'), ('None', 'None'), ('Race', 'Race'), ('Stress Relief', 'Stress Relief'), ('Workout', 'Workout')], default='None', max_length=15)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('workout_intensity', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Moderate'), ('Hard', 'Hard')], default='Medium', max_length=10)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
